version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./infra/docker/api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - LEXICAL_WEIGHT=0.5
      - VECTOR_WEIGHT=0.3
      - CF_WEIGHT=0.2
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2

  ui:
    build:
      context: .
      dockerfile: ./infra/docker/ui.Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    depends_on:
      - api
